general {
	ignore_empty_input = true
}

background {
	monitor =
	path = screenshot
	color = rgba(0, 0, 0, 0.7)
	blur_passes = 3
}

input-field {
	monitor =
	size = 350, 50
	outline_thickness = 3
	inner_color = rgba(0, 0, 0, 0.5)

  outer_color = rgba(a6e3a1ee) rgba(89b4faee) 135deg
	check_color = rgba(89b4faee) rgba(fab387ee) 135deg
	fail_color = rgba(fab387ee) rgba(f38ba8ee) 135deg

	font_color = rgb(210, 210, 210)
	fade_on_empty = false
	rounding = 15

	position = 0, -20
	halign = center
	valign = center
}
