term xterm-256color
enable_audio_bell no
shell zsh
shell_integration disabled
sync_to_monitor no

# Cursor settings
cursor_trail 10
cursor_trail_start_threshold 0
cursor_trail_decay 0.01 0.15
cursor_shape block
cursor_blink true
