hide_window_decorations yes
background_opacity 0.8

enabled_layouts splits

scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0

confirm_os_window_close 0

remember_window_size no
